// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./../components/Card.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IconCarbonAperture: typeof import('~icons/carbon/aperture')['default']
    IconCarbonAssetConfirm: typeof import('~icons/carbon/asset-confirm')['default']
    IconEpLocationFilled: typeof import('~icons/ep/location-filled')['default']
    IconSvgAccount: typeof import('~icons/svg/account')['default']
    IconSvgLocation: typeof import('~icons/svg/location')['default']
    IconSvgMenuFold: typeof import('~icons/svg/menu-fold')['default']
    IconSvgOfficial: typeof import('~icons/svg/official')['default']
    IconTypcnAnchorOutline: typeof import('~icons/typcn/anchor-outline')['default']
    VIcon: typeof import('./../components/VIcon.vue')['default']
  }
}
